# Generated by Django 5.1.7 on 2025-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EventName", models.CharField(help_text="Event Name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the event"
                    ),
                ),
                ("date", models.DateTimeField(help_text="Date and time of event")),
                (
                    "location",
                    models.CharField(help_text="Event location", max_length=200),
                ),
            ],
        ),
    ]
