# Generated by Django 5.1.7 on 2025-03-25 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="EventName",
            field=models.CharField(help_text="Event name", max_length=200),
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("GuestName", models.CharField(help_text="Guest name", max_length=200)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the guest",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event the guest is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="EventManagement.events",
                    ),
                ),
            ],
        ),
    ]
