FROM python:3.12-slim

WORKDIR /workspace

RUN pip install poetry

COPY pyproject.toml .

COPY . . 

RUN poetry install --no-root -nq

ENTRYPOINT [ "poetry", "run", "uvicorn" ]

CMD [ "session_13.main:api", "--host" ,"0.0.0.0" ]